<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New</name>
   <tag></tag>
   <elementGuidId>d229bf5e-1c79-44f4-a55e-82926432836a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.d-flex-item.nav--main.nav--has-megamenu.nav--new.is-expanded > a.nav__link.nav__link-main.nav-lv1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='section-header']/div[2]/nav/ul/li[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;New&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a245c29-6a63-4aeb-9a1b-de0aba4c7894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/whats-new-480</value>
      <webElementGuid>a19641b0-0972-42cc-a7c8-4617bddc0219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>aa15fd8d-be78-44a7-8c7f-418f0fc001fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav__link nav__link-main nav-lv1</value>
      <webElementGuid>ef8a1f08-a42d-4f84-bc52-46725092c179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            New
          </value>
      <webElementGuid>26ee7ff7-f344-4233-8949-160a03ff4b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-header&quot;)/div[@class=&quot;site-nav__wrapper site-nav__blue&quot;]/nav[@class=&quot;site-nav&quot;]/ul[@class=&quot;sed-flex flex-center&quot;]/li[@class=&quot;d-flex-item nav--main nav--has-megamenu nav--new is-expanded&quot;]/a[@class=&quot;nav__link nav__link-main nav-lv1&quot;]</value>
      <webElementGuid>e87d5ee4-8529-48e3-b7b5-346592f1db6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='section-header']/div[2]/nav/ul/li[10]/a</value>
      <webElementGuid>d771e0fb-7532-4966-9310-cbc035352f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'New')])[2]</value>
      <webElementGuid>ffc38a0e-9cb1-4b43-986e-e6496770f257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footwear'])[1]/following::a[2]</value>
      <webElementGuid>1cc79ced-c593-4c29-8d48-c46f28a26bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clothing'])[2]/following::a[3]</value>
      <webElementGuid>89072468-6c15-4ab9-89df-d1faf14a03cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[60]/preceding::a[1]</value>
      <webElementGuid>188f5a82-8985-4dc6-91bf-746985960ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Arrivals'])[1]/preceding::a[2]</value>
      <webElementGuid>5982dda1-7e71-46ed-bcf5-4a09cc1e2905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New']/parent::*</value>
      <webElementGuid>e7e9b375-e0cb-477c-a4fa-9fc4e2c36f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/collections/whats-new-480')]</value>
      <webElementGuid>ffaa877d-7968-4549-8140-2b1d699b30f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>1e009993-ccf9-40c2-8f04-16e2c4b65ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/whats-new-480' and @title = 'New' and (text() = '
            New
          ' or . = '
            New
          ')]</value>
      <webElementGuid>a6586321-04ab-47a2-a525-289705a2bb44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
