<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sale</name>
   <tag></tag>
   <elementGuidId>7b08cd0a-af17-4afb-9e98-7f5a6711c5ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.d-flex-item.nav--main.nav--has-megamenu.nav--sale.is-expanded > a.nav__link.nav__link-main.nav-lv1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='section-header']/div[2]/nav/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Sale&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cbcf59c4-5651-4d35-9033-7cfa749e480a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/sale-481</value>
      <webElementGuid>6deb6283-871d-4b7e-b347-0a9bc8fff0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sale</value>
      <webElementGuid>53c6a274-3e8c-40f0-9428-b720d4551610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav__link nav__link-main nav-lv1</value>
      <webElementGuid>538da426-94d1-438b-8f1e-c577ddde4195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Sale
          </value>
      <webElementGuid>210266a5-75ae-4adb-b752-29eac5c10fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-header&quot;)/div[@class=&quot;site-nav__wrapper site-nav__blue&quot;]/nav[@class=&quot;site-nav&quot;]/ul[@class=&quot;sed-flex flex-center&quot;]/li[@class=&quot;d-flex-item nav--main nav--has-megamenu nav--sale is-expanded&quot;]/a[@class=&quot;nav__link nav__link-main nav-lv1&quot;]</value>
      <webElementGuid>947a21c6-2d4e-48a0-b1eb-ed6556de263c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='section-header']/div[2]/nav/ul/li[9]/a</value>
      <webElementGuid>5baf1b06-8c83-4d59-a9a5-decf2bb35b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sale')]</value>
      <webElementGuid>18c787b3-04e7-44dc-a2df-f88dcc22cdbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oxygen Units'])[2]/following::a[1]</value>
      <webElementGuid>ce8868b3-d273-4bf0-a3fc-cc5af770c809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Megaphones'])[3]/following::a[2]</value>
      <webElementGuid>fd1e0fd2-f8af-4c10-a10c-a2fd408156e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[56]/preceding::a[1]</value>
      <webElementGuid>08b38cbb-4a6c-49ff-8a35-a85f400fcd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*hide - Shop All Sale'])[1]/preceding::a[2]</value>
      <webElementGuid>4d397268-6589-4b2b-bf32-8ccc5da13f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sale']/parent::*</value>
      <webElementGuid>dc3533e0-21fa-4d10-9392-6bb0b2e6a5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/collections/sale-481')]</value>
      <webElementGuid>f9ca077e-04df-4ad5-91df-291389a160f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[9]/a</value>
      <webElementGuid>83a1a5ce-1e30-4778-b966-f75c58a99094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/sale-481' and @title = 'Sale' and (text() = '
            Sale
          ' or . = '
            Sale
          ')]</value>
      <webElementGuid>8f1b2d6d-96d4-451e-b4a6-e365e9c8088d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
